project_id = "acadeai"
[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000
[db]
port = 54322
shadow_port = 54320
major_version = 15
[db.seed]
enabled = false
[studio]
enabled = false
[local_smtp]
enabled = true
port = 54324
[storage]
enabled = true
[auth]
enabled = true
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["http://127.0.0.1:5173/**"]
jwt_expiry = 3600
signing_keys_path = "./.local/signing_keys.json"
enable_signup = false
[auth.email.template.invite]
subject = "Seu convite para AcadeAI"
content_path = "./supabase/templates/invite.html"
[auth.email.template.magic_link]
subject = "Acesse seu convite AcadeAI"
content_path = "./supabase/templates/magic-link.html"
[auth.email.template.recovery]
subject = "Recuperação de acesso AcadeAI"
content_path = "./supabase/templates/recovery.html"
[analytics]
enabled = false

